// GENERATED by apps/site/scripts/gen-guides.mjs from @mcpfold/adapters — DO NOT EDIT BY HAND.
// The config path (per OS), secret strategy, restart requirement, and remote capability are read
// live from the real adapters so a guide can never drift from what `mcpfold sync` actually writes.
// Regenerate with: pnpm --filter @mcpfold/site guides:gen  (drift-checked in CI via guides:check).

/** Secret-handling strategy a client uses (mirrors @mcpfold/adapters SecretStrategy). */
export type GuideSecretStrategy = 'inline' | 'native-input' | 'shim';

/** How a client names its remote-endpoint field, or 'shim' when it has no native remote support. */
export type GuideRemoteFieldShape = 'url' | 'type+url' | 'httpUrl' | 'shim';

/** Everything a per-client setup guide needs, frozen from adapter facts at build time. */
export interface GuideClient {
  readonly id: string;
  readonly label: string;
  /** The top-level key the client stores MCP servers under (e.g. `mcpServers`). */
  readonly configRoot: string;
  readonly secretStrategy: GuideSecretStrategy;
  readonly needsRestart: boolean;
  readonly remote: {
    readonly nativeHttp: boolean;
    readonly nativeOauth: boolean;
    readonly fieldShape: GuideRemoteFieldShape;
  };
  /** Example user-scope config path per OS (`null` if the client has no user-scope file). */
  readonly paths: {
    readonly macos: string | null;
    readonly windows: string | null;
    readonly linux: string | null;
  };
}

/** Every client mcpfold can fold config out to, in the canonical adapter order. */
export const GUIDE_CLIENTS: readonly GuideClient[] = [
  {
    "id": "claude-code",
    "label": "Claude Code",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "type+url"
    },
    "paths": {
      "macos": "/Users/you/.claude.json",
      "windows": "C:\\Users\\you\\.claude.json",
      "linux": "/home/you/.claude.json"
    }
  },
  {
    "id": "claude-desktop",
    "label": "Claude Desktop",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": true,
    "remote": {
      "nativeHttp": false,
      "nativeOauth": false,
      "fieldShape": "shim"
    },
    "paths": {
      "macos": "/Users/you/Library/Application Support/Claude/claude_desktop_config.json",
      "windows": "C:\\Users\\you\\AppData\\Roaming\\Claude\\claude_desktop_config.json",
      "linux": "/home/you/.config/Claude/claude_desktop_config.json"
    }
  },
  {
    "id": "cursor",
    "label": "Cursor",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.cursor/mcp.json",
      "windows": "C:\\Users\\you\\.cursor\\mcp.json",
      "linux": "/home/you/.cursor/mcp.json"
    }
  },
  {
    "id": "vscode",
    "label": "VS Code",
    "configRoot": "servers",
    "secretStrategy": "native-input",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "type+url"
    },
    "paths": {
      "macos": "/Users/you/Library/Application Support/Code/User/mcp.json",
      "windows": "C:\\Users\\you\\AppData\\Roaming\\Code\\User\\mcp.json",
      "linux": "/home/you/.config/Code/User/mcp.json"
    }
  },
  {
    "id": "windsurf",
    "label": "Windsurf",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": true,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": false,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.codeium/windsurf/mcp_config.json",
      "windows": "C:\\Users\\you\\.codeium\\windsurf\\mcp_config.json",
      "linux": "/home/you/.codeium/windsurf/mcp_config.json"
    }
  },
  {
    "id": "zed",
    "label": "Zed",
    "configRoot": "context_servers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.config/zed/settings.json",
      "windows": "C:\\Users\\you\\AppData\\Roaming\\Zed\\settings.json",
      "linux": "/home/you/.config/zed/settings.json"
    }
  },
  {
    "id": "cline",
    "label": "Cline",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json",
      "windows": "C:\\Users\\you\\AppData\\Roaming\\Code\\User\\globalStorage\\saoudrizwan.claude-dev\\settings\\cline_mcp_settings.json",
      "linux": "/home/you/.config/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"
    }
  },
  {
    "id": "gemini-cli",
    "label": "Gemini CLI",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "httpUrl"
    },
    "paths": {
      "macos": "/Users/you/.gemini/settings.json",
      "windows": "C:\\Users\\you\\.gemini\\settings.json",
      "linux": "/home/you/.gemini/settings.json"
    }
  },
  {
    "id": "jetbrains",
    "label": "JetBrains",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.junie/mcp/mcp.json",
      "windows": "C:\\Users\\you\\.junie\\mcp\\mcp.json",
      "linux": "/home/you/.junie/mcp/mcp.json"
    }
  },
  {
    "id": "visual-studio",
    "label": "Visual Studio",
    "configRoot": "servers",
    "secretStrategy": "native-input",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "type+url"
    },
    "paths": {
      "macos": "/Users/you/.mcp.json",
      "windows": "C:\\Users\\you\\.mcp.json",
      "linux": "/home/you/.mcp.json"
    }
  },
  {
    "id": "continue",
    "label": "Continue",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.continue/mcpServers/mcpfold.json",
      "windows": "C:\\Users\\you\\.continue\\mcpServers\\mcpfold.json",
      "linux": "/home/you/.continue/mcpServers/mcpfold.json"
    }
  },
  {
    "id": "roo-code",
    "label": "Roo Code",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/Library/Application Support/Code/User/globalStorage/rooveterinaryinc.roo-cline/settings/cline_mcp_settings.json",
      "windows": "C:\\Users\\you\\AppData\\Roaming\\Code\\User\\globalStorage\\rooveterinaryinc.roo-cline\\settings\\cline_mcp_settings.json",
      "linux": "/home/you/.config/Code/User/globalStorage/rooveterinaryinc.roo-cline/settings/cline_mcp_settings.json"
    }
  },
  {
    "id": "goose",
    "label": "Goose",
    "configRoot": "extensions",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.config/goose/config.yaml",
      "windows": "C:\\Users\\you\\AppData\\Roaming\\Block\\goose\\config\\config.yaml",
      "linux": "/home/you/.config/goose/config.yaml"
    }
  },
  {
    "id": "codex-cli",
    "label": "Codex CLI",
    "configRoot": "mcp_servers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.codex/config.toml",
      "windows": "C:\\Users\\you\\.codex\\config.toml",
      "linux": "/home/you/.codex/config.toml"
    }
  },
  {
    "id": "lm-studio",
    "label": "LM Studio",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.lmstudio/mcp.json",
      "windows": "C:\\Users\\you\\.lmstudio\\mcp.json",
      "linux": "/home/you/.lmstudio/mcp.json"
    }
  },
  {
    "id": "warp",
    "label": "Warp",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.warp/.mcp.json",
      "windows": "C:\\Users\\you\\.warp\\.mcp.json",
      "linux": "/home/you/.warp/.mcp.json"
    }
  },
  {
    "id": "opencode",
    "label": "opencode",
    "configRoot": "mcp",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "url"
    },
    "paths": {
      "macos": "/Users/you/.config/opencode/opencode.json",
      "windows": "C:\\Users\\you\\.config\\opencode\\opencode.json",
      "linux": "/home/you/.config/opencode/opencode.json"
    }
  },
  {
    "id": "copilot-cli",
    "label": "Copilot CLI",
    "configRoot": "mcpServers",
    "secretStrategy": "shim",
    "needsRestart": false,
    "remote": {
      "nativeHttp": true,
      "nativeOauth": true,
      "fieldShape": "type+url"
    },
    "paths": {
      "macos": "/Users/you/.copilot/mcp-config.json",
      "windows": "C:\\Users\\you\\.copilot\\mcp-config.json",
      "linux": "/home/you/.copilot/mcp-config.json"
    }
  }
];

/** Look up a guide by client id. */
export function guideById(id: string): GuideClient | undefined {
  return GUIDE_CLIENTS.find((c) => c.id === id);
}
